Feature/basic functionalities
yayawallet/yayawallet-java-sdk pull request #2
Opened 2024-03-24 21:42 UTC by ermiyas111

2024-03-24 22:23 UTC, agebeyaw requested changes

2024-03-24 22:23 UTC, agebeyaw commented on src/Services/Transaction.java
> +        HttpResponse<String> response = apiClient.apiRequest("GET", "/transaction/find-by-user", "?p=1", null);
what about getting the page number as param, defaulting to 1 if not specified?

2024-03-24 22:23 UTC, agebeyaw commented on src/Services/Transaction.java
> +package Services;
is it possible to have a root namespace appended, like `YaYa/Sdk/` or `YaYaSdk` so the package be like `YaYa/Sdk/Service` or `YaYaSdk/Service`?

2024-03-24 22:23 UTC, agebeyaw commented on src/ApiRequest/ApiClient.java
> +    private static final String API_URL = System.getenv("API_URL");
May be some integrations use this SDK along with other SDKs in their system and better to name the env variables explicitly referencing YaYa, so the env variable names be better like `YAYA_API_URL`, `YAYA_API_KEY`, etc

2024-04-18 16:16 UTC, agebeyaw reviewed
Airtime service seem not yet implemented, can you add that as well?

2024-04-18 16:16 UTC, agebeyaw commented on src/Main.java
do we need this class if it just prints hello world?

2024-04-18 16:16 UTC, agebeyaw commented on src/com/yaya/sdk/Services/Transfer.java
> +        HttpResponse<String> response = apiClient.apiRequest("GET", "/transfer/", "", null);
you can alternatively use `transfer/list` if you want to avoid the trailing slash

2024-04-19 10:24 UTC, ermiyas111 commented
> Airtime service seem not yet implemented, can you add that as well?

Buying airtime is not working

2024-04-29 11:56 UTC, agebeyaw approved these changes

2024-04-29 11:56 UTC, agebeyaw commented on README.md
> +# yaya-python
`yaya-java` ?

2024-04-30 06:45 UTC, merged